### ISSUE TITLE
Tests on mac

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#155]
CSharp fail, what need install? I try install mono last version, but then test freeze, i try wait, no finish after 6 hours.
```
CppTest > testBigTest FAILED
    java.lang.RuntimeException at CppTest.kt:37

CSharpTest > testMicroStaticInitTestAsm1 FAILED
    java.io.IOException at CSharpTest.kt:54
        Caused by: java.io.IOException at CSharpTest.kt:54

CSharpTest > testBig FAILED
    java.io.IOException at CSharpTest.kt:45
        Caused by: java.io.IOException at CSharpTest.kt:45

CSharpTest > testAsyncIO FAILED
    java.io.IOException at CSharpTest.kt:62
        Caused by: java.io.IOException at CSharpTest.kt:62

CSharpTest > testMicroHelloWorldAsm FAILED
    java.io.IOException at CSharpTest.kt:38
        Caused by: java.io.IOException at CSharpTest.kt:38

CSharpTest > testServiceLoaderTest FAILED
    java.io.IOException at CSharpTest.kt:40
        Caused by: java.io.IOException at CSharpTest.kt:40

CSharpTest > testHelloWorld FAILED
    java.io.IOException at CSharpTest.kt:35
        Caused by: java.io.IOException at CSharpTest.kt:35

92 tests completed, 7 failed, 36 skipped
:jtransc-main:test FAILED

```

For CppTest in results next log
```
java.lang.RuntimeException: success=false
exitCode=127
output=''
error='./autogen.sh: line 15: autoreconf: command not found
'
	at com.jtransc.gen.cpp.libs.Lib.runCommand(Lib.kt:43)
	at com.jtransc.gen.cpp.libs.BdwgcLib.install(BdwgcLib.kt:49)
	at com.jtransc.gen.cpp.libs.Lib.installIfRequired(Lib.kt:19)
	at com.jtransc.gen.cpp.libs.Libs.installIfRequired(Libs.kt:32)
	at com.jtransc.gen.cpp.CppGenerator.compile(CppTarget.kt:110)
	at com.jtransc.gen.common.CommonGenerator.compileAndRun(CommonGenerator.kt:149)
	at com.jtransc.gen.GenTargetDescriptor.build(gen.kt:104)
	at com.jtransc.JTranscBuild._buildAndRun(build.kt:160)
	at com.jtransc.JTranscBuild.buildAndRunCapturingOutput(build.kt:86)
	at _Base._action(_Base.kt:178)
	at _Base.action(_Base.kt:121)
	at _Base.testClassNoLog(_Base.kt:84)
	at _Base.testClass(_Base.kt:64)
	at CppTest.testBigTest(CppTest.kt:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Help me configure my system, i update readme file.

**Comment by soywiz** [comment]
C# probably related to this: https://github.com/jtransc/jtransc/blob/master/.travis.yml#L2
It seems to be a bug in mono. Not sure which versions of mono. Can you `mcs --version` to check in internet if there are known hangs for that version?

Related to pure C++ target on mac:
```
brew install automake
```

**Comment by SergeyLabutin** [comment]
I can not build via XCode
```

Showing Recent Issues
 - /usr/local/lib/haxe/lib/hxcpp/3,4,64/src/hx/NoFiles.cpp 


 - src/__resources__.cpp 


Error: clang: error: unable to execute command: Killed: 9


clang: error: clang frontend command failed due to signal (use -v to see invocation)


Apple LLVM version 8.1.0 (clang-802.0.42)


Target: x86_64-apple-darwin16.6.0


Thread model: posix


InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin



Showing Recent Issues
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.


clang: note: diagnostic msg: 


********************


PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:


Preprocessed source(s) and associated run script(s) are located at:


clang: note: diagnostic msg: /var/folders/zx/hj7thw9n7tn1nzypb1s3pc_40000gn/T/ProgramReflection_AllClasses_-4ed8b4.cpp


clang: note: diagnostic msg: /var/folders/zx/hj7thw9n7tn1nzypb1s3pc_40000gn/T/ProgramReflection_AllClasses_-4ed8b4.sh


clang: note: diagnostic msg: Crash backtrace is located in


clang: note: diagnostic msg: /Users/sergey/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash


clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)


clang: note: diagnostic msg: 


********************


make: *** [build-haxe-x86_64] Error 254


Command /Applications/Xcode.app/Contents/Developer/usr/bin/make failed with exit code 2

```

**Comment by soywiz** [comment]
Is this a separate issue? It happens with Haxe/C++? It is a large project? Maybe it is an out of memory?

**Comment by SergeyLabutin** [comment]
Yes, second problem on with my big project. Maybe need separate, i create new after find new info. About first issue:
I buy new mac with i7, 16Gb RAM, SSD. If install mono freeze again, without same errors.

**Comment by soywiz** [comment]
For that you can do the following:

Use jvisualvm to do a heap snapshot of the jtransc compilation project. Maybe you can figure out classes that have lots of instances or spending a lot of memory and i can figure out how to optimize it.

The other thing you can try, is to execute jtransc to generate haxe. Then cancel when haxe is compiling to cpp. Then `./gradlew --stop` and execute haxe (or lime) manually. That way clang/gcc will have more memory since gradle is stopped. If it works we know that it is an out of memory.

**Comment by SergeyLabutin** [comment]
Create new issues for each problem.
