### ISSUE TITLE
Cpp BigTest failed

### ISSUE THREAD

**Issue by SergeyLabutin** [jtransc/jtransc#163]
After update project i get error on Windows
`Command line error D8021: invalid numeric argument '/Wno-parentheses-equality'`
Full log:
```
java.lang.RuntimeException: success=false exitCode=1 output='Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 05.06.2017 12:07:40.
Project "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" (1) is building "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "Win32\Debug\ZERO_CHECK\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ZERO_CHECK.vcxproj]
  Creating directory "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\Debug\".
  Creating directory "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/Users/serge/AppData/Local/Temp/jtransc/0_0/jtransc-cpp/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ZERO_CHECK.vcxproj" (default targets).
Project "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" (1) is building "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "program.dir\Debug\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj]
  Creating directory "program.dir\Debug\program.tlog\".
InitializeBuildStatus:
  Creating "program.dir\Debug\program.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Building Custom Rule C:/Users/serge/AppData/Local/Temp/jtransc/0_0/jtransc-cpp/CMakeLists.txt
  CMake does not need to re-run because C:/Users/serge/AppData/Local/Temp/jtransc/0_0/jtransc-cpp/CMakeFiles/generate.stamp is up-to-date.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe /c /I"C:\Users\serge\.jtransc\cpp\0_6_3-snapshot\bdwgc\include" /Zi /nologo /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D GC_NOT_DLL=1 /D USE_BOEHM_GC=1 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"program.dir\Debug\\" /Fd"program.dir\Debug\vc141.pdb" /Gd /TP /analyze- /errorReport:queue   -Wno-parentheses-equality -Wno-unused-value "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.cpp"
cl : Command line error D8021: invalid numeric argument '/Wno-parentheses-equality' [C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj]
Done Building Project "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ZERO_CHECK.vcxproj" (default target) (2) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ZERO_CHECK.vcxproj]


"C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj" (default target) (3) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(395,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj]


"C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj" (default target) (3) ->
(ClCompile target) -> 
  cl : Command line error D8021: invalid numeric argument '/Wno-parentheses-equality' [C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp\program.vcxproj]

    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.57' error='' folder=C:\Users\serge\AppData\Local\Temp\jtransc\0_0\jtransc-cpp command='C:\tools\CMake\bin\cmake.exe --build . --config Debug'
	at com.jtransc.gen.common.CommonGenerator.compile(CommonGenerator.kt:135)
	at com.jtransc.gen.cpp.CppGenerator.compile(CppTarget.kt:111)
	at com.jtransc.gen.common.CommonGenerator.compileAndRun(CommonGenerator.kt:150)
	at com.jtransc.gen.GenTargetDescriptor.build(gen.kt:104)
	at com.jtransc.JTranscBuild._buildAndRun(build.kt:160)
	at com.jtransc.JTranscBuild.buildAndRunCapturingOutput(build.kt:86)
	at _Base._action(_Base.kt:178)
	at _Base.action(_Base.kt:121)
	at _Base.testClassNoLog(_Base.kt:84)
	at _Base.testClass(_Base.kt:64)
	at CppTest.testBigTest(CppTest.kt:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by intrigus** [comment]
Sorry, my fault.

**Comment by soywiz** [comment]
It's normal. I usually break things. That's because we usually develop on linux, mac or windows. The main problem here is that travis is not testing windows. I see two options here: install wine on travis and try adding a msvc compiler. Or try again to use appveyor that allows to test on a windows machine. That way we can have almost immeditate feedback (~10 min) about this kind of regressions.

**Comment by intrigus** [comment]
Why has appveyor been disabled in the first place? 
Probably due to some problems with setting everything up? 
If so, I'd be fine with appveyor only testing the c++ target

**Comment by soywiz** [comment]
I disabled it because i was not able to configure it properly. But PRs are welcome :)
