### ISSUE TITLE
Inner lambda not working

### ISSUE THREAD

**Issue by marciodel** [jtransc/jtransc#170]
The test below generates an error.
When using retrolambda the error didn't occur.

```
package tests;

import java.util.function.BiConsumer;
import java.util.function.Function;

public class InnerLambdaTest {

	public static void main(String[] args) {
		setTimeout(()->{
			System.out.println("Test 1");
		}, 1000);

		Promise promise = new Promise((resolve, reject)->{
			
			setTimeout(()->{
				System.out.println("Test 2");
			}, 1000);

			
			setTimeout(()->{
				resolve.apply("!!");
			}, 1000);

		});
		
	}
	
	static void setTimeout(Runnable run, double millis){
		try {
			Thread.sleep((long) millis);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		run.run();
	}

	static class Promise {
		public Promise(BiConsumer<Function<String, String>, Function<String, String>> exec) {
			exec.accept((str) -> {
				System.out.println("Resolved " + str);
				return "";
			}, (str) -> {
				System.out.println("Rejected " + str);
				return "";
			});
		}
	}

}
```
Error:
```
Test 1
program.js:8576 Test 2
program.js:11817 TypeError: Cannot read property 'apply(Ljava/lang/Object;)Ljava/lang/Object;' of null
    at Function.tests_InnerLambdaTest.lambda$null$2(Ljava/util/function/Function;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11595:4)
    at L$3.run()V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:1569:72)
    at Function.tests_InnerLambdaTest.setTimeout(Ljava/lang/Runnable;D)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11622:19)
    at Function.tests_InnerLambdaTest.lambda$main$3(Ljava/util/function/Function;Ljava/util/function/Function;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11591:61)
    at L$1.accept(Ljava/lang/Object;Ljava/lang/Object;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:1628:101)
    at tests_InnerLambdaTest$Promise.tests.InnerLambdaTest$Promise<init>(Ljava/util/function/BiConsumer;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:6314:53)
    at Function.tests_InnerLambdaTest.main([Ljava/lang/String;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11585:80)
    at file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11815:53
    at file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11822:3
(anonymous) @ program.js:11817
(anonymous) @ program.js:11822
program.js:11818 TypeError: Cannot read property 'apply(Ljava/lang/Object;)Ljava/lang/Object;' of null
    at Function.tests_InnerLambdaTest.lambda$null$2(Ljava/util/function/Function;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11595:4)
    at L$3.run()V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:1569:72)
    at Function.tests_InnerLambdaTest.setTimeout(Ljava/lang/Runnable;D)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11622:19)
    at Function.tests_InnerLambdaTest.lambda$main$3(Ljava/util/function/Function;Ljava/util/function/Function;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11591:61)
    at L$1.accept(Ljava/lang/Object;Ljava/lang/Object;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:1628:101)
    at tests_InnerLambdaTest$Promise.tests.InnerLambdaTest$Promise<init>(Ljava/util/function/BiConsumer;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:6314:53)
    at Function.tests_InnerLambdaTest.main([Ljava/lang/String;)V (file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11585:80)
    at file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11815:53
    at file:///C:/Users/marci/Desenv/Workspaces/workspaceKotlin/elemental2-jtransc-samples/jtransc-tests/build/jtransc-js/program.js:11822:3
```

**Comment by soywiz** [comment]
Going to test asap. Even when JTransc supports java8 lambdas, since I'm mostly using Kotlin (that probably does probably what retrolambda does) it is not battle tested yet. So I will add this test and fix it. I have planned to focus on java8 features for like a couple of weeks or so to try to find all these things, but no specific schedule for that. In the mean time I will fix this.
Thanks for reporting!

**Comment by soywiz** [comment]
I'm working on this already. This is the offending generated code:

It seems that it uses a local variable that it is not initialized `lA0` (so it is null). I suspect the problem is in the `invokedynamic` generator.

```
jtransc_java8_InnerLambdaTest["lambda$main$3(Ljava/util/function/Function;Ljava/util/function/Function;)V"] = function(p0, p1) { 
	var lA0 = null;
	jtransc_java8_InnerLambdaTest["setTimeout(Ljava/lang/Runnable;D)V"]((new L$2())["L$2<init>()V"](), 100.0);
	jtransc_java8_InnerLambdaTest["setTimeout(Ljava/lang/Runnable;D)V"]((new L$3())["L$3<init>(Ljava/lang/Object;)V"](lA0), 100.0);
	return;
};
```
