### ISSUE TITLE
Gradle central NoSuchKey error

### ISSUE THREAD

**Issue by davidsusu** [jtransc/jtransc#281]
My project setup fails because this url responses a `NoSuchKey` error:

https://plugins.gradle.org/m2/gradle/plugin/com/jtransc/jtransc-gradle-plugin/0.6.7/jtransc-gradle-plugin-0.6.7.pom

**Comment by soywiz** [comment]
If you are using gradle plugin. As a workaround you can grab it fron central. Using this syntax:

https://github.com/jtransc/jtransc/blob/master/benchmark/build.gradle

I will try to upload latest version to gradle plugins too

**Comment by davidsusu** [comment]
I have no luck. I tried the build script linked by you, however, after a successful init, when I run one of the gensrc task I get the following exception every time:

```
com.jtransc.error.InvalidOperationException: AstProgram. Can't find class 'Benchmark'
	at com.jtransc.ast.AstProgram.get(ast.kt:233)
	at com.jtransc.ast.treeshaking.TreeShakingApi.<init>(TreeShaking.kt:42)
	at com.jtransc.ast.treeshaking.TreeShakingKt.TreeShaking(TreeShaking.kt:17)
	at com.jtransc.JTranscBuild._buildAndRun(build.kt:138)
	at com.jtransc.JTranscBuild.buildWithoutRunning(build.kt:88)
	at com.jtransc.gradle.tasks.JTranscGradleDistTask.task(JTranscGradleDistTask.kt:17)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	... 77 more
```
