### ISSUE TITLE
Using jtransc from cli doesn't work

### ISSUE THREAD

**Issue by intrigus** [jtransc/jtransc#47]
Hi, I'm trying the example from [here](https://github.com/jtransc/jtransc/tree/master/jtransc-main-run/example)
I'm running it like this:
`../jtransc . -main HelloWorld -release -out program.swf -run`
But it fails with 
````bash
Unable to parse command line options: Unrecognized option: -main

usage: mvn [options] [<goal(s)>] [<phase(s)>]
````

**Comment by soywiz** [comment]
Should be fixed

**Comment by intrigus** [comment]
````java
$ ./run
mvn -q -f ../pom.xml exec:java -Dexec.workingdir=/Users/simon/Documents/workspace_mars/jtransc/jtransc-main-run/example -Dexec.args=. -main HelloWorld -release -out program.js -run
java.lang.Exception: Unknown target auto
	at com.jtransc.BuildKt.locateTargetByName(build.kt:39)
	at com.jtransc.JTranscMain$main$5.invoke(main.kt:131)
	at com.jtransc.JTranscMain.main(main.kt:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by soywiz** [comment]
You have to `mvn install -DskipTests` jtransc git first
